### ISSUE TITLE
cant use it 

### ISSUE THREAD

**Issue by spix18** [hmz777/NetStalkerAvalonia#9]
![hS1U7w4vtH](https://github.com/hmz777/NetStalkerAvalonia/assets/7613901/50f89a59-a89b-4f7f-be9f-5c55e032d1b5)
im stuck in this windows for both alpha 1 and alpha 2

**Comment by hmz777** [comment]
You should download [Npcap](https://nmap.org/download.html) first. Notice how the driver version is not detected.
